---
- name: Download jsonnet package
  get_url:
    url: "https://github.com/google/jsonnet/releases/download/v0.14.0/jsonnet-bin-v0.14.0-linux.tar.gz"
    checksum: "{{ item.checksum }}"
    dest: "{{ download_tmp_directory }}/jsonnet-bin-v0.14.0-linux.tar.gz"
- name: Extract jsonnet binaries
  unarchive:
    src: "{{ download_tmp_directory }}/jsonnet-bin-v0.14.0-linux.tar.gz"
    dest: /usr/local/bin
    mode: 0755
    remote_src: True
    extra_opts:
    - --strip=2
