---
- name: Install Development Tools Group
  package: 
    name: "@Development tools"
    state: present
- name: Install C Development Tools and Libraries Group
  package:
    name: "@C Development Tools and Libraries"
    state: present
  when: ansible_os_family != 'RedHat' or ansible_distribution_major_version != '7'
- name: Install packages
  package:
    name:
    - tree
    - s3cmd
    - php-markdown
    - vim-enhanced
    - neovim
    - screen
    - bash
    - bash-completion
    - ruby-devel
    - zlib-devel
    - fuse-exfat
    - exfat-utils
    - nano
    - htop
    - jq
    - pcsc-tools # for ledger gpg card
    - docker
    - sshpass
    - clang-tools-extra # for clangd
    - fzf
    - awscli
    - moreutils

- name: Install modern packages
  package:
    name:
     - go
     - dep
     - git-lfs
     - ripgrep
     - python3-virtualenv
     - ShellCheck
  when: ansible_os_family != 'RedHat' or ansible_distribution_major_version != '7'

- name: Setup ledger udev rules
  template:
    src: 20-hw1.rules
    dest: /etc/udev/rules.d/20-hw1.rules
  register: ledger_rules
  when: local_user is defined

- name: Trigger udev
  command: >
    udevadm trigger
  when:
    - ledger_rules.changed
    - local_user is defined

- name: Reload udev
  command: >
    udevadm control --reload-rules
  when:
    - ledger_rules.changed
    - local_user is defined

  # Something tells me this should be last but ledger docs has it first, so just do both
- name: Trigger udev
  command: >
    udevadm trigger
  when:
    - ledger_rules.changed
    - local_user is defined

- include_tasks: dhall.yml
- include_tasks: jsonnet.yml
